EMAIL_WELCOME = "Welcome to our loyalty program! You're starting out at '{}' status."
EMAIL_GUEST_CANCELED = "Sorry, your guest has already canceled their account."
EMAIL_GUEST_INVITED = "Congratulations! Your guest has been invited!"
EMAIL_INSUFFICIENT_POINTS = "Sorry, you need to earn more points to invite more guests!"
EMAIL_PROMOTED = "Congratulations! _You've been promoted to '{}' status!"
EMAIL_CANCEL_ACCOUNT = "Sorry to see you go!"
EMAIL_DEMOTED = "Unfortunately, you've lost enough points to bump you down to '{}' status. 😞"
